echo insert Disk #5
pause
copy d:\drgraf\Elem_Dlg\*.cpp    b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.spp    b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.clw    b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.def    b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.rc     b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.mak    b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.bat    b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.h  	 b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\*.sh  	 b:\Elem_Dlg\*.*
copy d:\drgraf\Elem_Dlg\res\*.*  b:\Elem_Dlg\res\*.*
copy d:\drgraf\Elem_Dlg\hlp\*.*  b:\Elem_Dlg\hlp\*.*


