echo insert ZipDisk 
pause
copy c:\drgraf4_0\*.*                           S:\drgraf4_0\*.*
copy c:\drgraf4_0\DataBase\*.*                  S:\drgraf4_0\DataBase\*.*
copy c:\drgraf4_0\DataBase\res\*.*              S:\drgraf4_0\DataBase\res\*.*
copy c:\drgraf4_0\AuxiObjs\*.*                  S:\drgraf4_0\AuxiObjs\*.*
copy c:\drgraf4_0\Draw3D\*.*                    S:\drgraf4_0\Draw3D\*.*
copy c:\drgraf4_0\Specials\*.*                  S:\drgraf4_0\Specials\*.*
copy c:\drgraf4_0\GenObjs\*.*                   S:\drgraf4_0\GenObjs\*.*
copy c:\drgraf4_0\DrawObjs\*.*                  S:\drgraf4_0\DrawObjs\*.*
copy c:\drgraf4_0\DrawObjs\Dlg\*.*   			S:\drgraf4_0\DrawObjs\Dlg\*.*
copy c:\drgraf4_0\MeshObj\*.*					S:\drgraf4_0\MeshObj\*.*
copy c:\drgraf4_0\ElemObjs\*.*                  S:\drgraf4_0\ElemObjs\*.*
copy c:\drgraf4_0\ElemObjs\Inc\*.*   			S:\drgraf4_0\ElemObjs\Inc\*.*
copy c:\drgraf4_0\SuppObjs\*.*                  S:\drgraf4_0\SuppObjs\*.*
copy c:\drgraf4_0\StaLObjs\*.*                  S:\drgraf4_0\StaLObjs\*.*
copy c:\drgraf4_0\DynLObjs\*.*                  S:\drgraf4_0\DynLObjs\*.*
copy c:\drgraf4_0\SpeLObjs\*.*                  S:\drgraf4_0\SpeLObjs\*.*
copy c:\drgraf4_0\GrafMgr\*.*                   S:\drgraf4_0\GrafMgr\*.*
copy c:\drgraf4_0\Dr3D_Dlg\*.*                  S:\drgraf4_0\Dr3D_Dlg\*.*
copy c:\drgraf4_0\Spec_Dlg\*.*                  S:\drgraf4_0\Spec_Dlg\*.*
copy c:\drgraf4_0\Draw_Dlg\*.*                  S:\drgraf4_0\Draw_Dlg\*.*
copy c:\drgraf4_0\Elem_Dlg\*.*                  S:\drgraf4_0\Elem_Dlg\*.*
copy c:\drgraf4_0\ToolBoxs\DBoxEbox\*.* 		S:\drgraf4_0\ToolBoxs\DBoxEbox\*.*
copy c:\drgraf4_0\ToolBoxs\DBoxEbox\Res\*.*		S:\drgraf4_0\ToolBoxs\DBoxEbox\Res\*.*
copy c:\drgraf4_0\ToolBoxs\Drawbox\*.* 			S:\drgraf4_0\ToolBoxs\Drawbox\*.*
copy c:\drgraf4_0\ToolBoxs\Elembox\*.* 			S:\drgraf4_0\ToolBoxs\Elembox\*.*
copy c:\drgraf4_0\ToolBoxs\Elembox\Res\*.*		S:\drgraf4_0\ToolBoxs\Elembox\Res\*.*
copy c:\drgraf4_0\ToolBoxs\IGenbox\*.* 			S:\drgraf4_0\ToolBoxs\IGenbox\*.*
copy c:\drgraf4_0\ToolBoxs\IGenbox\Res\*.* 		S:\drgraf4_0\ToolBoxs\IGenbox\Res\*.*
copy c:\drgraf4_0\ToolBoxs\Inc\*.*              S:\drgraf4_0\ToolBoxs\Inc\*.*
copy c:\drgraf4_0\MouseMgr\*.*                  S:\drgraf4_0\MouseMgr\*.*
copy c:\drgraf4_0\MMgrNod\*.*                   S:\drgraf4_0\MMgrNod\*.*
copy c:\drgraf4_0\MMgrCur\*.*                   S:\drgraf4_0\MMgrCur\*.*
copy c:\drgraf4_0\MMgrPat\*.*                   S:\drgraf4_0\MMgrPat\*.*
copy c:\drgraf4_0\MMgrSol\*.*                   S:\drgraf4_0\MMgrSol\*.*
copy c:\drgraf4_0\MMgrO3D\*.*                   S:\drgraf4_0\MMgrO3D\*.*
copy c:\drgraf4_0\MMgrSupp\*.*                  S:\drgraf4_0\MMgrSupp\*.*
copy c:\drgraf4_0\MMgrStaL\*.*                  S:\drgraf4_0\MMgrStaL\*.*
copy c:\drgraf4_0\MMgrDynL\*.*                  S:\drgraf4_0\MMgrDynL\*.*
copy c:\drgraf4_0\MMgrSpeL\*.*                  S:\drgraf4_0\MMgrSpeL\*.*
copy c:\drgraf4_0\EditMgr\*.*					S:\drgraf4_0\EditMgr\*.*
copy c:\drgraf4_0\DelMgr\*.*					S:\drgraf4_0\DelMgr\*.*
copy c:\drgraf4_0\CreOpMgr\*.*                  S:\drgraf4_0\CreOpMgr\*.*
copy c:\drgraf4_0\PostMgr\*.*					S:\drgraf4_0\PostMgr\*.*
copy c:\drgraf4_0\MMgrMs0\*.*                   S:\drgraf4_0\MMgrMs0\*.*
copy c:\drgraf4_0\MMgrMs1\*.*                   S:\drgraf4_0\MMgrMs1\*.*
copy c:\drgraf4_0\MMgrMs2\*.*                   S:\drgraf4_0\MMgrMs2\*.*
copy c:\drgraf4_0\MMgrMs3\*.*                   S:\drgraf4_0\MMgrMs3\*.*
copy c:\drgraf4_0\MMgrM3D\*.*                   S:\drgraf4_0\MMgrM3D\*.*
copy c:\drgraf4_0\CreOmMgr\*.*                  S:\drgraf4_0\CreOmMgr\*.*
copy c:\drgraf4_0\CreOmMgr\Res\*.*              S:\drgraf4_0\CreOmMgr\Res\*.*
copy c:\drgraf4_0\MditMgr\*.*                   S:\drgraf4_0\MditMgr\*.*
copy c:\drgraf4_0\MditMgr\Res\*.*               S:\drgraf4_0\MditMgr\Res\*.*
copy c:\drgraf4_0\DeckMgr\*.*					S:\drgraf4_0\DeckMgr\*.*
copy c:\drgraf4_0\View\*.*                      S:\drgraf4_0\View\*.*
copy c:\drgraf4_0\ViewDlg\*.*                   S:\drgraf4_0\ViewDlg\*.*
copy c:\drgraf4_0\Applic\*.*                    S:\drgraf4_0\Applic\*.*
copy c:\drgraf4_0\Applic\Res\*.*                S:\drgraf4_0\Applic\Res\*.*
copy c:\drgraf4_0\DataBase\*.*                  S:\drgraf4_0\DataBase\*.*
copy c:\drgraf4_0\DataBase\Res\*.*              S:\drgraf4_0\DataBase\Res\*.*
copy c:\drgraf4_0\InSpect\*.*					S:\drgraf4_0\InSpect\*.*
copy c:\drgraf4_0\InSpect\Res\*.*				S:\drgraf4_0\InSpect\Res\*.*
copy c:\drgraf4_0\Document\*.*                  S:\drgraf4_0\Document\*.*
copy c:\drgraf4_0\Document\Inc\*.*  			S:\drgraf4_0\Document\Inc\*.*
copy c:\drgraf4_0\Frame\*.*                     S:\drgraf4_0\Frame\*.*
copy c:\drgraf4_0\Frame\Inc\*.*                 S:\drgraf4_0\Frame\Inc\*.*
copy c:\drgraf4_0\AllHeads\*.*                  S:\drgraf4_0\Allheads\*.*
copy c:\drgraf4_0\GlobHead\*.*                  S:\drgraf4_0\Globhead\*.*
copy c:\drgraf4_0\inc\*.*                       S:\drgraf4_0\inc\*.*
copy c:\drgraf4_0\res\*.*                       S:\drgraf4_0\res\*.*
copy c:\drgraf4_0\hlp\*.*                       S:\drgraf4_0\hlp\*.*
echo Done SUCCESSFULLY ZipDisk


