echo off
echo                           ToolBoxes:DBoxEBox will be copied... Disk #4
echo                                                    INSERT...   Disk #4     
call d:\drgraf\toolboxs\dboxebox\flop2dsk
echo                            ToolBoxes:DRAWBox will be copied... Disk #4
call d:\drgraf\toolboxs\drawbox\flop2dsk
echo                            ToolBoxes:ELEMBox will be copied... Disk #4
call d:\drgraf\toolboxs\elembox\flop2dsk
echo on

