echo off
echo                                  DRAWObjects will be copied... Disk #3
echo                                                    INSERT...   Disk #3     
call d:\drgraf\drawobjs\flop2dsk
echo                                     SPECIALS will be copied... Disk #3
call d:\drgraf\specials\flop2dsk
echo                                     Draw_Dlg will be copied... Disk #3
call d:\drgraf\draw_dlg\flop2dsk
echo                                     Spec_Dlg will be copied... Disk #3
call d:\drgraf\spec_dlg\flop2dsk
echo on

