echo off
echo                                       DRGRAF will be copied... Disk #1
echo                                                         Insert Disk #1       
call d:\drgraf\flop2dsk
echo                                       FRAME will be copied... Disk #1
call d:\drgraf\frame\flop2dsk
echo                                       VIEW will be copied... Disk #1
call d:\drgraf\view\flop2dsk
echo                                       DOCUMENT will be copied... Disk #1
call d:\drgraf\document\flop2dsk
echo on

