echo off
echo                                       DRGRAF will be copied... Disk #1
echo                                                         Insert Disk #1       
call d:\drgraf\cop2flop
echo                                       FRAME will be copied... Disk #1
call d:\drgraf\frame\cop2flop
echo                                       VIEW will be copied... Disk #1
call d:\drgraf\view\cop2flop
echo                                       DOCUMENT will be copied... Disk #1
call d:\drgraf\document\c{^ÐŒ¹U{^ÐŒ¹U{^Ð