echo off
echo                                                    INSERT...   Disk #3     
echo                                  	 DRAWObjects will be copied... Disk #3
call d:\drgraf\drawobjs\cop2flop
echo                                     SPECIALS will be copied... Disk #3
call d:\drgraf\specials\cop2flop
echo                                     Draw_Dlg will be copied... Disk #3
call d:\drgraf\draw_dlg\cop2flop
echo                                     Spec_Dlg will be copied... Disk #3
call d:\drgraf\spec_dlg\cop2flop
echo on

