echo off
echo                           ToolBoxes:DBoxEBox will be copied... Disk #4
echo                                                    INSERT...   Disk #4     
call d:\drgraf\toolboxs\dboxebox\cop2flop
echo                            ToolBoxes:DRAWBox will be copied... Disk #4
call d:\drgraf\toolboxs\drawbox\cop2flop
echo                            ToolBoxes:ELEMBox will be copied... Disk #4
call d:\drgraf\toolboxs\elembox\cop2flop
echo on

