echo insert Disk #1
pause
copy b:\drgraf\*.cpp    d:\drgraf\*.*
copy b:\drgraf\*.spp    d:\drgraf\*.*
copy b:\drgraf\*.clw    d:\drgraf\*.*
copy b:\drgraf\*.def    d:\drgraf\*.*
copy b:\drgraf\*.rc     d:\drgraf\*.*
copy b:\drgraf\*.mak    d:\drgraf\*.*
copy b:\drgraf\*.bat    d:\drgraf\*.*
copy b:\drgraf\*.h  	d:\drgraf\*.*
copy b:\drgraf\*.sh  	d:\drgraf\*.*
copy b:\drgraf\inc\*.h  d:\drgraf\inc\*.*
copy b:\drgraf\res\*.*  d:\drgraf\res\*.*
copy b:\drgraf\hlp\*.*  d:\drgraf\hlp\*.*


