echo off
echo insert Disk #3
pause
copy d:\drgraf\specials\*.cpp    b:\specials\*.*
copy d:\drgraf\specials\*.spp    b:\specials\*.*
copy d:\drgraf\specials\*.clw    b:\specials\*.*
copy d:\drgraf\specials\*.def    b:\specials\*.*
copy d:\drgraf\specials\*.rc     b:\specials\*.*
copy d:\drgraf\specials\*.mak    b:\specials\*.*
copy d:\drgraf\specials\*.bat    b:\specials\*.*
copy d:\drgraf\specials\*.h      b:\specials\*.*
copy d:\drgraf\specials\*.sh     b:\specials\*.*
copy d:\drgraf\specials\dlg\*.*  b:\specials\dlg\*.*
copy d:\drgraf\specials\res\*.*  b:\specials\res\*.*
copy d:\drgraf\specials\hlp\*.*  b:\specials\hlp\*.*
echo on

