echo insert Disk #1
pause
copy d:\drgraf\document\*.cpp    b:\drgraf\document\*.*
copy d:\drgraf\document\*.spp    b:\drgraf\document\*.*
copy d:\drgraf\document\*.clw    b:\drgraf\document\*.*
copy d:\drgraf\document\*.def    b:\drgraf\document\*.*
copy d:\drgraf\document\*.rc     b:\drgraf\document\*.*
copy d:\drgraf\document\*.mak    b:\drgraf\document\*.*
copy d:\drgraf\document\*.bat    b:\drgraf\document\*.*
copy d:\drgraf\document\*.h  	 b:\drgraf\document\*.*
copy d:\drgraf\document\*.sh  	 b:\drgraf\document\*.*
copy d:\drgraf\document\inc\*.h  b:\drgraf\document\inc\*.*
copy d:\drgraf\document\res\*.*  b:\drgraf\document\res\*.*
copy d:\drgraf\document\hlp\*.*  b:\drgraf\document\hlp\*.*


