// drgradoc.cpp : implementation of the CDrGrafDoc class
//

#include "stdafx.h"

#include "drgradoc.h"

#ifdef _DEBUG
#undef THIS_FILE
static char BASED_CODE THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////// INITIALIZE 
void CDrGrafDoc::SerialDocument(CArchive& ar)
{ 
	////////////////////////////////  STORING				
	if (ar.IsStoring())
	{
	}
	////////////////////////////////  LOADING				
	else
	{
	}
				    				
}
