//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IGenBox.rc
//
#define IDS_CHECK_RESOURCE              1
#define IDB_MNODBOX                     200
#define IDB_MGENBOX                     201
#define IDB_MCNODBOX                    203
#define IDC_BUTTON                      211
#define IDB_NODE                        1001
#define IDB_PATCH                       1012
#define IDB_TENSOR                      1099
#define IDB_COONS                       1013
#define IDB_MESH                        1013
#define IDB_ROTATE                      1014
#define IDB_LOFT                        1015
#define IDB_EXTRUDE                     1016
#define IDB_DUCT                        1017
#define IDB_SWEEP                       1018
#define IDB_FLATPLATE                   1020
#define IDB_P_EDIT                      1021
#define IDB_P_MOVE                      1022
#define IDB_N_EDIT                      1023
#define IDB_N_MOVE                      1024
#define IDB_MOVE                        1024
#define IDB_CURVE                       1025
#define IDB_C_CIRCLE                    1026
#define IDB_C_ELLIPSE                   1027
#define IDB_C_PARABOLA                  1028
#define IDB_C_LINEAR                    1029
#define IDB_C_QUADRATIC                 1030
#define IDB_C_HERMITE                   1031
#define IDB_C_BEZIER                    1032
#define IDB_C_BSPLINE                   1033
#define IDB_C_EDIT                      1034
#define IDB_C_MOVE                      1035
#define IDB_CNODE                       1036
#define IDB_P_POST                      1037
#define IDB_C_POST                      1038
#define IDB_N_POST                      1039
#define IDB_SOLID                       1040
#define IDB_COONS_S                     1041
#define IDB_MESH_S                      1041
#define IDB_ROTATE_S                    1042
#define IDB_LOFT_S                      1043
#define IDB_EXTRUDE_S                   1044
#define IDB_DUCT_S                      1045
#define IDB_SWEEP_S                     1046
#define IDB_S_EDIT                      1049
#define IDB_S_MOVE                      1050
#define IDB_S_POST                      1051
#define IDB_OBJ3D                       1052
#define IDB_P_UNPOST                    1053
#define IDB_S_UNPOST                    1054
#define IDB_N_UNPOST                    1055
#define IDB_C_UNPOST                    1056
#define IDB_C_NURB                      1060
#define IDB_C_DELETE                    1061
#define IDB_N_DELETE                    1062
#define IDB_S_DELETE                    1063
#define IDB_P_DELETE                    1064
#define IDB_S_STITCH                    1065
#define IDB_S_SPAWN                     1066
#define IDB_P_STITCH                    1071
#define IDB_P_SPAWN                     1072
#define IDB_C_STITCH                    1077
#define IDB_C_SPAWN                     1078
#define IDB_GORDON                      1098
#define IDB_GORDON_S                    1100
#define IDB_C_OPER                      1102
#define IDB_S_OPER                      1103
#define IDB_P_OPER                      1104
#define IDB_N_OPER                      1105
#define IDB_MNODE                       1123
#define IDB_FE0D                        1124
#define IDB_N_SUPP                      1146
#define IDB_P_SUPP                      1147
#define IDB_S_SUPP                      1148
#define IDB_C_SUPP                      1149
#define IDB_N_STAL                      1150
#define IDB_P_STAL                      1151
#define IDB_S_STAL                      1152
#define IDB_C_STAL                      1153
#define IDB_N_DYNL                      1154
#define IDB_P_DYNL                      1155
#define IDB_S_DYNL                      1156
#define IDB_C_DYNL                      1157
#define IDB_N_SPEL                      1158
#define IDB_P_SPEL                      1159
#define IDB_ELEMENT                     1159
#define IDB_GENOPS                      1160
#define IDB_S_SPEL                      1160
#define IDB_FEMOPS                      1161
#define IDB_C_SPEL                      1161
#define IDB_BULLOPS                     1162
#define IDB_EDIM_0                      1163
#define IDB_EDIM_1                      1164
#define IDB_EDIM_2                      1165
#define IDB_EDIM_3                      1166
#define IDB_CREATEOPS                   1167
#define IDB_RESERVE                     9999
#define IDB_INODE                       10010
#define IDB_MCNODE                      11242
#define IDB_MESH3D                      11591
#define IDB_MESH2D                      11592
#define IDB_MESH1D                      11593
#define IDB_MESH0D                      11594
#define IDB_MBJ3D                       11595
#define IDB_GOP_EDIT                    11601
#define IDB_GOP_MOVE                    11602
#define IDB_GOP_POST                    11603
#define IDB_GOP_UNPOST                  11604
#define IDB_GOP_DELETE                  11605
#define IDB_GOP_MERGE                   11606
#define IDB_COP_CREATE                  11671
#define IDB_COP_TRANSLATE               11672
#define IDB_COP_ROTATE                  11673
#define IDB_COP_SCALE                   11674
#define IDB_COP_REFLECT                 11675
#define IDB_COP_SHEAR                   11676
#define IDB_COP_SPAWN                   11677
#define IDB_COP_STITCH                  11678
#define IDB_COP_BLEND					11679
#define IDB_COP_EXTRACT					11680

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32825
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           146
#endif
#endif
