echo insert Disk #4
pause
copy d:\drgraf\toolboxs\elembox\inc\*.h   	   b:\drgraf\toolboxs\elembox\inc\*.*
copy d:\drgraf\toolboxs\elembox\*.h 	  	   b:\drgraf\toolboxs\elembox\inc\*.*
copy d:\drgraf\toolboxs\elembox\*.sh 	  	   b:\drgraf\toolboxs\elembox\inc\*.*
copy d:\drgraf\toolboxs\elembox\*.cpp          b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.spp          b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.clw          b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.def          b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.rc           b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.mak          b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.bat          b:\drgraf\toolboxs\elembox\*.*
copy d:\drgraf\toolboxs\elembox\res\*.*        b:\drgraf\toolboxs\elembox\res\*.*
copy d:\drgraf\toolboxs\elembox\hlp\*.*        b:\drgraf\toolboxs\elembox\hlp\*.*


