echo insert Disk #3
pause
copy d:\drgraf\drawobjs\*.cpp    b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.spp    b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.clw    b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.def    b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.rc     b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.mak    b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.bat    b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.h 	 b:\drawobjs\*.*
copy d:\drgraf\drawobjs\*.sh 	 b:\drawobjs\*.*
copy d:\drgraf\drawobjs\dlg\*.*  b:\drawobjs\dlg\*.*
copy d:\drgraf\drawobjs\inc\*.*  b:\drawobjs\inc\*.*


