echo insert Disk #3
pause
copy d:\drgraf\Draw_Dlg\*.cpp    b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.spp    b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.clw    b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.def    b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.rc     b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.mak    b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.bat    b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.h  	 b:\Draw_Dlg\*.*
copy d:\drgraf\Draw_Dlg\*.sh  	 b:\Draw_Dlg\*.*


