//Control-specific messages
#define ELM_NODE     (WM_USER+21)       // Node
#define ELM_PIPE     (WM_USER+22)       // Pipe
#define ELM_ELBOW    (WM_USER+23)       // Elbow
#define ELM_BEAM     (WM_USER+24)       // Beam
#define ELM_SUPPORT  (WM_USER+25)       // SubLibrary:SUPPORT 
#define ELM_TRUSS    (WM_USER+26)       // Truss
#define ELM_PLANE    (WM_USER+27)       // Plane
#define ELM_PLATE    (WM_USER+28)       // PLate
#define ELM_SHELL    (WM_USER+29)       // Shell
