echo insert Disk #7
pause
copy d:\drgraf\grafmgr\*.cpp    b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.spp    b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.clw    b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.def    b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.rc     b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.mak    b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.bat    b:\grafmgr\*.*
copy d:\drgraf\grafmgr\inc\*.h  b:\grafmgr\inc\*.*
copy d:\drgraf\grafmgr\*.h      b:\grafmgr\*.*
copy d:\drgraf\grafmgr\*.sh     b:\grafmgr\*.*
copy d:\drgraf\grafmgr\res\*.*  b:\grafmgr\res\*.*
copy d:\drgraf\grafmgr\hlp\*.*  b:\drgraf\grafmgr\hlp\*.*


