echo insert Disk #0
pause
copy d:\drgraf\applic\*.cpp    b:\applic\*.*
copy d:\drgraf\applic\*.spp    b:\applic\*.*
copy d:\drgraf\applic\*.clw    b:\applic\*.*
copy d:\drgraf\applic\*.def    b:\applic\*.*
copy d:\drgraf\applic\*.rc     b:\applic\*.*
copy d:\drgraf\applic\*.mak    b:\applic\*.*
copy d:\drgraf\applic\*.bat    b:\applic\*.*
copy d:\drgraf\applic\*.h      b:\applic\*.*
copy d:\drgraf\applic\*.sh     b:\applic\*.*
copy d:\drgraf\applic\inc\*.h  b:\applic\inc\*.*
copy d:\drgraf\applic\res\*.*  b:\applic\res\*.*
copy d:\drgraf\applic\hlp\*.*  b:\applic\hlp\*.*


