//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Drgraf.rc
//
#define IDS_CHECK_RESOURCE              1
#define IDR_MAINFRAME                   2
#define IDR_DRGRAFTYPE                  3
#define IDR_INPUTMENU                   3
#define IDR_OUTPUTMENU                  4
#define IDR_12TYPE                      5
#define IDR_23TYPE                      6
#define IDR_31TYPE                      7
#define IDR_3DTYPE                      8
#define IDR_DATATYPE                    9
#define IDR_VIEW12                      10
#define IDR_VIEW23                      11
#define IDR_VIEW31                      12
#define IDR_VIEW3D                      13
#define IDR_VIEWDAT                     14
#define IDR_VIEWUNKNOWN                 15
#define IDS_TOO_MANY_ROWS               15
#define IDR_MESHDATATYPE                16
#define IDR_DECKTYPE                    17
#define IDR_DRGRAFTYPE_CNTR_IP          18
#define IDR_FORMDATATYPE                19
#define IDC_PARAMETERS_FACTOR           75
#define IDC_PARAMETERS_FIX              76
#define IDC_PARAMETERS_UNITS            77
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDC_LIST                        101
#define IDP_FAILED_TO_CREATE            102
#define IDB_SPLASH                      103
#define IDB_DRCAFE                      104
#define IDB_SEASHORE                    105
#define IDB_JASMIN                      106
#define IDD_SHRINKON                    109
#define IDS_TOP_STATUSBAR               111
#define IDD_NOSHOW_LABEL_ELEM           111
#define IDS_BOT_STATUSBAR               112
#define IDD_NOSHOW_ELEM                 112
#define IDR_DISTRIBINPUT                113
#define IDR_AUXINPUT                    113
#define IDR_AUXINPUTMENU                113
#define IDM_VIEW_STATUS_BAR_B           115
#define IDM_VIEW_STATUS_BAR_T           116
#define IDD_PROBELEMLIM                 116
#define IDS_CNTLSTAT                    117
#define IDD_DEFAULTS                    117
#define IDS_IGENSTAT                    118
#define IDD_ELEMENTS                    118
#define IDS_OPERSTAT                    119
#define IDS_DRAWSTAT                    120
#define IDS_CURRSTAT                    121
#define IDS_BLINESTAT                   122
#define IDS_AUTOACCEPTSTAT              123
#define IDS_SINGLESEGSTAT               124
#define IDS_SPAWNSTAT                   125
#define IDS_SNAPSTAT                    126
#define IDS_MODESTAT                    127
#define IDC_DISK_SPACE                  207
#define IDC_BUTTON                      211
#define IDC_AVAIL_MEM                   259
#define IDD_SPLASH                      266
#define IDC_MATH_COPR                   269
#define IDC_SHRINK                      361
#define IDC_BEAM                        1001
#define IDC_PIPE                        1002
#define IDC_ELBOW                       1003
#define IDC_TRUSS                       1004
#define IDC_QU_4                        1005
#define IDC_QU_8                        1006
#define IDC_QU_9                        1007
#define IDC_BIGICON                     1008
#define IDC_QU_12                       1008
#define IDS_DISK_SPACE                  1009
#define IDC_QU_16                       1009
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDC_TR_3                        1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDC_TR_6                        1011
#define IDS_AVAIL_MEM                   1012
#define IDC_TR_9                        1012
#define IDS_LICENSEE_COMPANY            1013
#define IDC_TR_10                       1013
#define IDS_LICENSEE_NAME               1014
#define IDC_BALLJT                      1014
#define IDC_NOSHOW_ALL                  1015
#define IDC_NOSHOW_NONE                 1016
#define IDC_TETRA                       1017
#define IDS_DISK_SPACE_UNAVAIL          1018
#define IDC_PENTA                       1018
#define IDC_HEXA                        1019
#define IDC_COMBOPROBDIM                1020
#define IDC_COMBOELEMDIM                1021
#define IDD_TIMING_DLG                  1720
#define IDM_SPEC_EYELEVEL               32752
#define IDM_SPEC_LAYER                  32753
#define ID_CANCEL_EDIT                  32754
#define ID_CANCEL_EDIT_CNTR             32755
#define ID_CANCEL_EDIT_SRVR             32756
#define IDM_VIEW_12VIEW                 32760
#define IDM_VIEW_23VIEW                 32761
#define IDM_VIEW_31VIEW                 32770
#define IDM_VIEW_3DVIEW                 32771
#define IDM_3D_EYEPOSITION              32773
#define IDM_3D_LIGHTSOURCE              32774
#define IDM_SPEC_PAPER                  32775
#define IDM_SPEC_PRECISION              32776
#define IDM_3D_PROJECTION               32777
#define IDM_SPEC_AXIS                   32778
#define IDM_SPEC_UNITS                  32779
#define IDM_SPEC_EYEPOSITION            32780
#define IDM_SPEC_SCALEFACTOR            32781
#define IDM_DEFAULT_NEW                 32782
#define IDM_DEFAULT_CURRENT             32783
#define IDM_OPTION_CURSOR               32784
#define IDM_SPEC_MAG_XMAG               32785
#define IDM_SPEC_MAG_YMAG               32786
#define IDM_3D_PROJECTION_PARALLEL      32787
#define IDM_SPEC_MAG_ZMAG               32788
#define IDM_VIEW_DRAWBOX                32789
#define IDM_VIEW_ELEMENTBOX             32790
#define IDM_OPTION_DIALOG               32791
#define IDM_3D_PROJECTION_PERSPECTIVE   32791
#define IDM_OPTION_REFRESH              32792
#define IDM_3D_WIREFRAMED               32793
#define IDM_OPTION_AXISON               32794
#define IDM_OPTION_DIALOGON             32795
#define IDM_3D_RENDERING                32796
#define IDM_3D_AMBIENTLIGHT             32797
#define IDM_OPTION_RUBBERBAND           32798
#define IDM_3D_FLATSHADING              32800
#define IDM_3D_ZBUFFERED                32801
#define IDM_ZOOM_FIT                    32802
#define IDM_MESH_BSPL                   32803
#define IDM_MESH_BEZI                   32804
#define IDM_EDIT_CLEAR_ALL              32806
#define IDM_SPEC_OBJ3D                  32807
#define IDM_SPEC_PATCH                  32808
#define IDM_DECK_DREAMPIPE              32819
#define IDM_ZOOM                        32820
#define IDM_OPTION_PENCHANGE            32821
#define IDM_NOSHOW_NODES                32822
#define IDM_NOSHOW_CNODES               32823
#define IDM_NODELABEL                   32824
#define IDM_NOSHOW_CNLABEL              32825
#define IDM_NOSHOW_NLABEL               32827
#define IDM_VIEW_CARDDECK               32828
#define IDM_NOSHOW_NORMALS              32828
#define IDM_VIEW_DATAVIEW               32829
#define IDM_DECK_SAP                    32830
#define IDM_DECK_TAB                    32831
#define IDM_VIEW_S_BAR_BOT              32832
#define IDM_VIEW_S_BAR_TOP              32833
#define IDM_NOSHOW_CONTROLSHAPE         32835
#define IDM_INPUT                       32836
#define IDM_MODE_OUTPUT                 32837
#define IDM_MODE_INPUT                  32838
#define IDM_3D_WF_PURE                  32841
#define IDM_3D_WF_HIDDEN                32843
#define IDM_3D_FS_PAINTER               32844
#define IDM_3D_FS_ZBUFFER               32845
#define IDM_3D_ZB_GOURAUD               32846
#define IDM_3D_ZB_PHONG                 32847
#define ID_NOSHOW_LABELS_2DSCREEN       32848
#define ID_NOSHOW_LABELS_3DPATCH        32849
#define IDM_ELEMENTS_NODE               32850
#define IDM_ELEMENTS_PIPE               32851
#define IDM_NOSHOW_2DLABEL              32851
#define IDM_ELEMENTS_BEAM               32852
#define IDM_NOSHOW_3DLABEL              32852
#define IDM_ELEMENTS_ELBOW              32853
#define IDM_ELEMENTS_SUPPORT            32854
#define ID_PICK_OBJECT                  32854
#define IDM_ELEMENTS_NL_SUPP            32855
#define ID_PICK_SOLID                   32855
#define ID_PICK_PATCH                   32856
#define ID_PICK_CURVE                   32857
#define ID_PICK_ELEMENTS                32858
#define ID_PICK_NODE                    32859
#define IDM_NOSHOW_CENTROID             32861
#define IDM_NOSHOW_DIRTY                32862
#define IDM_NOSHOW_POSTED               32863
#define IDM_NOSHOW_D_OBJECT             32864
#define IDM_NOSHOW_D_SOLID              32865
#define IDM_NOSHOW_D_PATCH              32866
#define IDM_NOSHOW_D_CURVE              32867
#define IDM_NOSHOW_P_PROFILE_C          32868
#define IDM_NOSHOW_P_PROFILE_P          32869
#define IDM_NOSHOW_P_PROFILE_S          32870
#define IDM_MODE_DESIGN                 32871
#define IDM_NOSHOW_P_OBJECT             32872
#define IDM_NOSHOW_P_SOLID              32873
#define IDM_NOSHOW_P_PATCH              32874
#define IDM_NOSHOW_P_CURVE              32875
#define IDM_NOSHOW_VC_VRP               32876
#define IDM_NOSHOW_VC_PRP               32877
#define IDM_NOSHOW_VC_VUP               32878
#define IDM_NOSHOW_VC_PLANE             32879
#define IDM_NOSHOW_VC_VPN               32880
#define IDM_NOSHOW_VC_WC                32881
#define IDM_NOSHOW_VC_WCS               32882
#define IDM_NOSHOW_VC_VCS               32883
#define IDM_NOSHOW_VC_VDIR              32884
#define IDM_NOSHOW_VC_FCP               32885
#define IDM_NOSHOW_VC_BCP               32886
#define IDM_NOSHOW_VC_CVV               32887
#define IDM_NOSHOW_VC_VV                32888
#define ID_PICK_MESHNODE                32889
#define IDM_MESH_HERM                   32890
#define IDM_NOSHOW_MNODES               32891
#define IDM_NOSHOW_MNLABEL              32893
#define IDM_NOSHOW_D_PROFILE_C          32896
#define IDM_NOSHOW_D_PROFILE_P          32897
#define IDM_NOSHOW_D_PROFILE_S          32898
#define IDM_MODE_INTERPOLATE            32899
#define IDM_MESH_OFF                    32900
#define IDM_MESH_QUAD                   32901
#define IDM_MESH_LINR                   32902
#define IDM_VIEW_MESHBOX                32903
#define ID_SUMMARY_OBJECT               32904
#define ID_SUMMARY_SOLID                32905
#define ID_SUMMARY_SOLID_DIRTY          32906
#define ID_SUMMARY_SOLID_POSTED         32907
#define ID_SUMMARY_PATCH_DIRTY          32908
#define ID_SUMMARY_PATCH_POSTED         32909
#define ID_SUMMARY_CURVE_DIRTY          32910
#define ID_SUMMARY_CURVE_POSTED         32911
#define ID_SUMMARY_ELEMENTS             32912
#define ID_SUMMARY_NODE_ALLTYPES        32913
#define ID_SUMMARY_NODE_CONTROL         32914
#define ID_SUMMARY_NODE_MESH            32915
#define IDM_3D_SHRINKON                 32916
#define IDM_3D_CULLINGON                32917
#define IDM_3D_CULLING3D                32918
#define IDM_OPTION_SOUNDON              32919
#define IDM_OPTION_AUTOACCEPTON         32920
#define IDM_OPTION_BLINEON              32921
#define IDM_OPTION_SINGLESEGON          32922
#define ID_PICK_LINEARSUPPORT_RIGID     32924
#define ID_PICK_LINEARSUPPORT_SPRING    32925
#define ID_PICK_LINEARSUPPORT_SNUBBER   32926
#define IDM_NOSHOW_LINEARSUPPORT_RIGID  32928
#define IDM_NOSHOW_LINEARSUPPORT_SPRING 32929
#define IDM_NOSHOW_LINEARSUPPORT_SNUBBER 32930
#define ID_SUMMARY_LINEARSUPPORT_RIGID  32931
#define ID_SUMMARY_LINEARSUPPORT_SPRING 32932
#define ID_SUMMARY_LINEARSUPPORT_SNUBBER 32933
#define IDM_NOSHOW_STATIC_FORCE         32934
#define IDM_NOSHOW_STATIC_DISPLACE      32935
#define IDM_NOSHOW_STATIC_PRESSURE      32936
#define IDM_NOSHOW_STATIC_THERMAL       32937
#define IDM_NOSHOW_STATIC_LUMPWT        32938
#define ID_SUMMARY_STATIC_FORCE         32939
#define ID_SUMMARY_STATIC_DISPLACE      32940
#define ID_SUMMARY_STATIC_PRESSURE      32941
#define ID_SUMMARY_STATIC_THERMAL       32942
#define ID_SUMMARY_STATIC_LUMPWT        32943
#define ID_SUMMARY_STATIC_GRAVITY       32944
#define IDM_NOSHOW_STATIC_GRAVITY       32945
#define IDM_VIEW_GENBOX                 32946
#define IDM_VIEW_CNTLBOX                32947
#define IDM_VIEW_OPTIONBOX              32948
#define IDM_VIEW_INPUTSTATUS_CURRENT    32949
#define IDM_VIEW_INPUTSTATUS_CONTROLS   32950
#define IDM_VIEW_INPUTSTATUS_GENERATOR  32951
#define IDM_VIEW_INPUTSTATUS_OPERATIONS 32952
#define IDM_VIEW_INPUTSTATUS_DECORATORS 32954
#define IDM_VIEW_OPERBOX                32955
#define ID_PICK_NODE_CONTROL            32957
#define IDM_NOSHOW_ELEMENTS             32958
#define IDM_SPEC_HITNET                 32959
#define ID_HELP_CONTENTS                32960
#define ID_NEW_WINDOW_3D                32961
#define IDM_WINDOW_NEW_3D_VIEW          32962
#define IDM_OPTION_SPAWNON              32963
#define IDM_VIEW_MODE_GENERATOR         32965
#define IDM_VIEW_MODE_MESH              32966
#define IDM_VIEW_MESHDATAVIEW           32967
#define IDM_DECK_FORMAT_FREE            32970
#define IDM_DECK_FORMAT_FIX             32971
#define IDM_DECK_FORMAT_FIXED           32971
#define IDM_VIEW_DECK                   32972
#define IDM_MODE_GENERATOR              32973
#define IDM_MODE_MESH                   32974
#define IDM_VIEW_DECKVIEW               32975
#define IDM_OPTION_NEWNODEON            32976
#define IDM_NOSHOW_LABEL_ELEMENTS       32977
#define IDM_DEBUG_CALCTIME              32978
#define ID_VIEW_REFRESH                 32979
#define IDM_VIEW_ALLVIEW                32980
#define ID_VIEW_DATABASE_AUXILLIARY     32981
#define IDM_VIEW_AUXILLIARY             32982
#define IDM_NOSHOW_KINEMATICSPECTRAHISTORIES_ACCELERATION 32983
#define IDM_NOSHOW_KINETIC_MASS         32984
#define IDM_NOSHOW_KINETIC_FORCE        32985
#define IDM_NOSHOW_KINETIC_PRESSURE     32986
#define IDM_NOSHOW_KINETIC_THERMAL      32987
#define IDM_NOSHOW_KINEMATICSPECTRAHISTORIES_DISPLACEMENT 32988
#define IDM_NOSHOW_KINEMATICSPECTRAHISTORIES_VELOCITY 32990
#define IDM_PICK_KINEMATICSPECTRAHISTORIES_DISPLACEMENT 32991
#define IDM_PICK_KINEMATICSPECTRAHISTORIES_VELOCITY 32992
#define IDM_PICK_KINEMATICSPECTRAHISTORIES_ACCELERATION 32993
#define IDM_PICK_KINETICSPECTRAHISTORIES_FORCE 32994
#define IDM_PICK_KINETICSPECTRAHISTORIES_PRESSURE 32995
#define IDM_PICK_KINETICSPECTRAHISTORIES_THERMAL 32996
#define IDM_MODE_DISTRIBUTION_SPATIAL   33000
#define IDM_MODE_AUXILLIARY_SPATIAL     33000
#define IDM_MODE_DISTRIBUTION_SPECTRAL  33001
#define IDM_MODE_AUXILLIARY_SPECTRAL    33001
#define IDM_MODE_DISTRIBUTION_TIME      33002
#define IDM_MODE_AUXILLIARY_TEMPORAL    33002
#define IDM_VIEW_SPECTRA                33003
#define IDM_VIEW_HISTORY                33005
#define IDM_VIEW_DATABASE_SPECTRAL      33008
#define IDM_VIEW_DATABASE_HISTORY       33009
#define IDM_OPTION_SNAPON               33011
#define IDM_OPTION_SNAPON_OBJMERG       33013
#define ID_OPTIONS_SNAPON_HORIZONTAL    33014
#define ID_OPTIONS_SNAPON_VERTICAL      33015
#define ID_VIEW_DATABASE_SHEETFORM      33016
#define IDM_VIEW_DATABASE_FORMDATA      33017
#define IDM_SPEC_DOUBLERATIO            33018
#define IDM_SPEC_COLINEAR               33019
#define IDM_SPEC_COPLANAR               33020
#define ID_NOSHOW_LABELS_LINEARSUPPORT  33021
#define ID_NOSHOW_LABELS_STATICLOADS    33022
#define IDM_NOSHOWLABELS_D_OBJECT       33023
#define IDM_NOSHOWLABELS_D_SOLID        33024
#define IDM_NOSHOWLABELS_D_PATCH        33025
#define IDM_NOSHOWLABELS_D_CURVE        33026
#define IDM_NOSHOWLABELS_P_PROFILE_C    33027
#define IDM_SPECS_TOLERANCES            33027
#define IDM_NOSHOWLABELS_P_PROFILE_P    33028
#define IDM_NOSHOWLABELS_LINEARSUPPORT_RIGID 33028
#define IDM_NOSHOWLABELS_P_PROFILE_S    33029
#define IDM_NOSHOWLABELS_LINEARSUPPORT_SPRING 33029
#define IDM_NOSHOWLABELS_P_OBJECT       33030
#define IDM_NOSHOWLABELS_LINEARSUPPORT_SNUBBER 33030
#define IDM_NOSHOWLABELS_P_SOLID        33031
#define IDM_NOSHOWLABELS_P_PATCH        33032
#define IDM_NOSHOWLABELS_P_CURVE        33033
#define IDM_NOSHOWLABELS_D_PROFILE_C    33034
#define IDM_NOSHOWLABELS_STATIC_FORCE   33034
#define IDM_NOSHOWLABELS_D_PROFILE_P    33035
#define IDM_NOSHOWLABELS_STATIC_DISPLACE 33035
#define IDM_NOSHOWLABELS_D_PROFILE_S    33036
#define IDM_NOSHOWLABELS_STATIC_PRESSURE 33036
#define IDM_NOSHOWLABELS_STATIC_THERMAL 33037
#define IDM_NOSHOWLABELS_STATIC_LUMPWT  33038
#define IDM_NOSHOWLABELS_STATIC_GRAVITY 33039
#define IDM_NOSHOWLABELS_KINEMATICSPECTRAHISTORIES_ACCELERATION 33040
#define IDM_NOSHOWLABELS_KINETIC_MASS   33041
#define IDM_NOSHOWLABELS_KINETIC_FORCE  33042
#define IDM_NOSHOWLABELS_KINETIC_PRESSURE 33043
#define IDM_NOSHOWLABELS_KINETIC_THERMAL 33044
#define IDM_NOSHOWLABELS_KINEMATICSPECTRAHISTORIES_DISPLACEMENT 33045
#define IDM_NOSHOWLABELS_KINEMATICSPECTRAHISTORIES_VELOCITY 33046
#define ID_INDICATOR_TEXT_X             59142
#define ID_INDICATOR_TEXT_Y             59144
#define ID_INDICATOR_TEXT_Z             59146
#define ID_INDICATOR_TEXT_LAYER         59148
#define ID_INDICATOR_TEXT_UNIT          59151
#define ID_INDICATOR_TEXT_TIME          59152
#define ID_INDICATOR_TEXT_DATE          59153
#define ID_INDICATOR_TEXT_DRAWING       59156

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        120
#define _APS_NEXT_COMMAND_VALUE         33028
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
