echo insert Disk #2
pause
copy d:\drgraf\Dr3D_Dlg\*.cpp    b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.spp    b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.clw    b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.def    b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.rc     b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.mak    b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.bat    b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.h      b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\*.sh     b:\Dr3D_Dlg\*.*
copy d:\drgraf\Dr3D_Dlg\res\*.*  b:\Dr3D_Dlg\res\*.*
copy d:\drgraf\Dr3D_Dlg\hlp\*.*  b:\Dr3D_Dlg\hlp\*.*


