//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by 3DLGRSRC.RC
//
#define IDC_SAMPLE                      131
#define IDC_INCREMENT                   132
#define IDC_PITCH                       160
#define IDC_ROLL                        161
#define IDC_YAW                         162

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         164
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
