//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DeckMgr.rc
//
#define IDS_CHECK_RESOURCE              1
#define IDD_OK                          1
#define UNFMT_NODE                      1
#define IDR_MAINFRAME                   2
#define UNFMT_CNODE                     2
#define IDR_DRGRAFTYPE                  3
#define IDR_INPUTMENU                   3
#define UNFMT_PIPE                      3
#define IDR_OUTPUTMENU                  4
#define UNFMT_ELBOW                     4
#define IDR_12TYPE                      5
#define UNFMT_BEAM                      5
#define IDR_23TYPE                      6
#define UNFMT_RIGIDSUP                  6
#define IDR_31TYPE                      7
#define IDR_3DTYPE                      8
#define IDR_DATATYPE                    9
#define IDR_DRGRAFTYPE_CNTR_IP          9
#define IDR_VIEW12                      10
#define IDR_VIEW23                      11
#define IDR_VIEW31                      12
#define IDD_FILE_PATH                   12
#define IDR_VIEW3D                      13
#define IDR_VIEWDAT                     14
#define IDR_VIEWUNKNOWN                 15
#define IDS_TOO_MANY_ROWS               15
#define IDR_MESHDATATYPE                16
#define IDD_PARAMETERS_XMIN             71
#define IDD_PARAMETERS_XMAX             72
#define IDD_PARAMETERS_YMIN             73
#define IDD_PARAMETERS_YMAX             74
#define IDC_PARAMETERS_FACTOR           75
#define IDC_PARAMETERS_FIX              76
#define IDC_PARAMETERS_UNITS            77
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDP_FAILED_TO_CREATE            102
#define IDB_SPLASH                      103
#define IDB_DRCAFE                      104
#define IDC_CURSOR1                     105
#define IDB_SEASHORE                    105
#define IDB_JASMIN                      106
#define IDD_SHRINKON                    109
#define IDS_TOP_STATUSBAR               111
#define IDC_DRAW_LIST                   111
#define IDS_BOT_STATUSBAR               112
#define IDC_TOGGLE_ALL                  113
#define IDM_VIEW_STATUS_BAR_B           115
#define IDM_VIEW_STATUS_BAR_T           116
#define IDS_CNTLSTAT                    117
#define IDS_IGENSTAT                    118
#define IDS_OPERSTAT                    119
#define IDS_DRAWSTAT                    120
#define IDS_CURRSTAT                    121
#define IDS_BLINESTAT                   122
#define IDS_AUTOACCEPTSTAT              123
#define IDS_SINGLESEGSTAT               124
#define IDS_SPAWNSTAT                   125
#define IDC_DRG_CURSOR                  131
#define IDD_LABEL_EDIT                  139
#define IDD_LIST                        144
#define IDD_EDIT_LABEL                  144
#define IDC_SCALE_FACTOR                145
#define IDC_EDIT                        152
#define IDC_PIX1                        159
#define IDC_DISK_SPACE                  207
#define IDC_BUTTON                      211
#define IDC_AVAIL_MEM                   259
#define IDC_LICENSEE_COMPANY            263
#define IDC_LICENSEE_NAME               265
#define IDD_SPLASH                      266
#define IDC_MATH_COPR                   269
#define IDC_SHRINK                      361
#define IDC_BIGICON                     1008
#define IDS_DISK_SPACE                  1009
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDS_AVAIL_MEM                   1012
#define IDS_LICENSEE_COMPANY            1013
#define IDS_LICENSEE_NAME               1014
#define IDS_DISK_SPACE_UNAVAIL          1018
#define IDM_SPEC_EYELEVEL               32752
#define IDM_SPEC_LAYER                  32753
#define ID_CANCEL_EDIT                  32754
#define ID_CANCEL_EDIT_CNTR             32755
#define ID_CANCEL_EDIT_SRVR             32756
#define IDM_VIEW_12VIEW                 32760
#define IDM_VIEW_23VIEW                 32761
#define IDM_VIEW_31VIEW                 32770
#define IDM_VIEW_3DVIEW                 32771
#define IDM_3D_EYEPOSITION              32773
#define IDM_3D_LIGHTSOURCE              32774
#define IDM_SPEC_PAPER                  32775
#define IDM_SPEC_PRECISION              32776
#define IDM_3D_PROJECTION               32777
#define IDM_SPEC_AXIS                   32778
#define IDM_SPEC_UNITS                  32779
#define IDM_SPEC_EYEPOSITION            32780
#define IDM_SPEC_SCALEFACTOR            32781
#define IDM_DEFAULT_NEW                 32782
#define IDM_DEFAULT_CURRENT             32783
#define IDM_OPTION_CURSOR               32784
#define IDM_SPEC_MAG_XMAG               32785
#define IDM_SPEC_MAG_YMAG               32786
#define IDM_3D_PROJECTION_PARALLEL      32787
#define IDM_SPEC_MAG_ZMAG               32788
#define IDM_VIEW_DRAWBOX                32789
#define IDM_VIEW_ELEMENTBOX             32790
#define IDM_OPTION_DIALOG               32791
#define IDM_3D_PROJECTION_PERSPECTIVE   32791
#define IDM_OPTION_REFRESH              32792
#define IDM_3D_WIREFRAMED               32793
#define IDM_OPTION_AXISON               32794
#define IDM_OPTION_DIALOGON             32795
#define IDM_3D_RENDERING                32796
#define IDM_EDIT_CLEARALL               32797
#define IDM_3D_AMBIENTLIGHT             32797
#define IDM_OPTION_RUBBERBAND           32798
#define IDM_3D_FLATSHADING              32800
#define IDM_3D_ZBUFFERED                32801
#define IDM_ZOOM_FIT                    32802
#define IDM_EDIT_CLEAR_ALL              32806
#define IDM_SPEC_OBJ3D                  32807
#define IDM_SPEC_PATCH                  32808
#define IDM_MESH_OFF                    32809
#define IDM_MESH_LIN                    32810
#define IDM_MESH_QUAD                   32811
#define IDM_MESH_HERMITE                32812
#define IDM_MESH_BEZ                    32813
#define IDM_MESH_BSP                    32814
#define IDM_MESH_HERM                   32815
#define IDM_MESH_BEZI                   32816
#define IDM_MESH_BSPL                   32817
#define IDM_MESH_LINR                   32818
#define IDM_DECK_DREAMPIPE              32819
#define IDM_ZOOM                        32820
#define IDM_OPTION_PENCHANGE            32821
#define IDM_NOSHOW_NODES                32822
#define IDM_NOSHOW_CNODES               32823
#define IDM_NODELABEL                   32824
#define IDM_NOSHOW_CNLABEL              32825
#define IDM_NOSHOW_NLABEL               32827
#define IDM_VIEW_CARDDECK               32828
#define IDM_NOSHOW_NORMALS              32828
#define IDM_VIEW_DATAVIEW               32829
#define IDM_DECK_SAP                    32830
#define IDM_DECK_TAB                    32831
#define IDM_VIEW_S_BAR_BOT              32832
#define IDM_VIEW_S_BAR_TOP              32833
#define IDM_NOSHOW_CONTROLSHAPE         32835
#define IDM_INPUT                       32836
#define IDM_MODE_OUTPUT                 32837
#define IDM_MODE_INPUT                  32838
#define IDM_3D_WF_CULL                  32839
#define IDM_3D_WF_PURE                  32841
#define IDM_3D_WF_HIDDEN                32843
#define IDM_3D_FS_PAINTER               32844
#define IDM_3D_FS_ZBUFFER               32845
#define IDM_3D_ZB_GOURAUD               32846
#define IDM_3D_ZB_PHONG                 32847
#define ID_NOSHOW_LABELS_2DSCREEN       32848
#define ID_NOSHOW_LABELS_3DPATCH        32849
#define IDM_ELEMENTS_NODE               32850
#define IDM_ELEMENTS_PIPE               32851
#define IDM_NOSHOW_2DLABEL              32851
#define IDM_ELEMENTS_BEAM               32852
#define IDM_NOSHOW_3DLABEL              32852
#define IDM_ELEMENTS_ELBOW              32853
#define IDM_ELEMENTS_SUPPORT            32854
#define ID_PICK_OBJECT                  32854
#define IDM_ELEMENTS_NL_SUPP            32855
#define ID_PICK_SOLID                   32855
#define ID_PICK_PATCH                   32856
#define ID_PICK_CURVE                   32857
#define ID_PICK_ELEMENTS                32858
#define ID_PICK_NODE                    32859
#define ID_PICK_CONTROLNODE             32860
#define IDM_NOSHOW_CENTROID             32861
#define IDM_NOSHOW_DIRTY                32862
#define IDM_NOSHOW_POSTED               32863
#define IDM_NOSHOW_D_OBJECT             32864
#define IDM_NOSHOW_D_SOLID              32865
#define IDM_NOSHOW_D_PATCH              32866
#define IDM_NOSHOW_D_CURVE              32867
#define IDM_NOSHOW_P_OBJECT             32872
#define IDM_NOSHOW_P_SOLID              32873
#define IDM_NOSHOW_P_PATCH              32874
#define IDM_NOSHOW_P_CURVE              32875
#define IDM_NOSHOW_VC_VRP               32876
#define IDM_NOSHOW_VC_PRP               32877
#define IDM_NOSHOW_VC_VUP               32878
#define IDM_NOSHOW_VC_PLANE             32879
#define IDM_NOSHOW_VC_VPN               32880
#define IDM_NOSHOW_VC_WC                32881
#define IDM_NOSHOW_VC_WCS               32882
#define IDM_NOSHOW_VC_VCS               32883
#define IDM_NOSHOW_VC_VDIR              32884
#define IDM_NOSHOW_VC_FCP               32885
#define IDM_NOSHOW_VC_BCP               32886
#define IDM_NOSHOW_VC_CVV               32887
#define IDM_NOSHOW_VC_VV                32888
#define ID_PICK_MESHNODE                32889
#define IDM_MESH_NURB                   32890
#define IDM_NOSHOW_MNODES               32891
#define IDM_NOSHOW_MNLABEL              32893
#define IDM_MODE_INTERPOLATE            32894
#define IDM_MODE_DESIGN                 32895
#define IDM_NOSHOW_D_PROFILE_C          32896
#define IDM_NOSHOW_D_PROFILE_P          32897
#define IDM_NOSHOW_D_PROFILE_S          32898
#define IDM_NOSHOW_P_PROFILE_P          32900
#define IDM_NOSHOW_P_PROFILE_C          32901
#define IDM_NOSHOW_P_PROFILE_S          32902
#define IDM_VIEW_MESHBOX                32903
#define ID_SUMMARY_OBJECT               32904
#define ID_SUMMARY_SOLID                32905
#define ID_SUMMARY_SOLID_DIRTY          32906
#define ID_SUMMARY_SOLID_POSTED         32907
#define ID_SUMMARY_PATCH_DIRTY          32908
#define ID_SUMMARY_PATCH_POSTED         32909
#define ID_SUMMARY_CURVE_DIRTY          32910
#define ID_SUMMARY_CURVE_POSTED         32911
#define ID_SUMMARY_ELEMENTS             32912
#define ID_SUMMARY_NODE_ALLTYPES        32913
#define ID_SUMMARY_NODE_CONTROL         32914
#define ID_SUMMARY_NODE_MESH            32915
#define IDM_3D_SHRINKON                 32916
#define IDM_3D_CULLINGON                32917
#define IDM_3D_CULLING3D                32918
#define IDM_OPTION_SOUNDON              32919
#define IDM_OPTION_AUTOACCEPTON         32920
#define IDM_OPTION_BLINEON              32921
#define IDM_OPTION_SINGLESEGON          32922
#define ID_PICK_LINEARSUPPORT_RIGID     32924
#define ID_PICK_LINEARSUPPORT_SPRING    32925
#define ID_PICK_LINEARSUPPORT_SNUBBER   32926
#define IDM_NOSHOW_LINEARSUPPORT_RIGID  32928
#define IDM_NOSHOW_LINEARSUPPORT_SPRING 32929
#define IDM_NOSHOW_LINEARSUPPORT_SNUBBER 32930
#define ID_SUMMARY_LINEARSUPPORT_RIGID  32931
#define ID_SUMMARY_LINEARSUPPORT_SPRING 32932
#define ID_SUMMARY_LINEARSUPPORT_SNUBBER 32933
#define IDM_NOSHOW_STATIC_FORCE         32934
#define IDM_NOSHOW_STATIC_DISPLACE      32935
#define IDM_NOSHOW_STATIC_PRESSURE      32936
#define IDM_NOSHOW_STATIC_THERMAL       32937
#define IDM_NOSHOW_STATIC_LUMPWT        32938
#define ID_SUMMARY_STATIC_FORCE         32939
#define ID_SUMMARY_STATIC_DISPLACE      32940
#define ID_SUMMARY_STATIC_PRESSURE      32941
#define ID_SUMMARY_STATIC_THERMAL       32942
#define ID_SUMMARY_STATIC_LUMPWT        32943
#define ID_SUMMARY_STATIC_GRAVITY       32944
#define IDM_NOSHOW_STATIC_GRAVITY       32945
#define IDM_VIEW_GENBOX                 32946
#define IDM_VIEW_CNTLBOX                32947
#define IDM_VIEW_OPTIONBOX              32948
#define IDM_VIEW_INPUTSTATUS_CURRENT    32949
#define IDM_VIEW_INPUTSTATUS_CONTROLS   32950
#define IDM_VIEW_INPUTSTATUS_GENERATOR  32951
#define IDM_VIEW_INPUTSTATUS_OPERATIONS 32952
#define IDM_VIEW_INPUTSTATUS_DECORATORS 32954
#define IDM_VIEW_OPERBOX                32955
#define ID_PICK_NODE_CONTROL            32957
#define IDM_NOSHOW_ELEMENTS             32958
#define IDM_SPEC_HITNET                 32959
#define ID_HELP_CONTENTS                32960
#define ID_NEW_WINDOW_3D                32961
#define IDM_WINDOW_NEW_3D_VIEW          32962
#define IDM_OPTION_SPAWNON              32963
#define IDM_VIEW_MODE_GENERATOR         32965
#define IDM_VIEW_MODE_MESH              32966
#define IDM_VIEW_MESHDATAVIEW           32967
#define ID_INDICATOR_TEXT_X             59142
#define ID_INDICATOR_X                  59143
#define ID_INDICATOR_TEXT_Y             59144
#define ID_INDICATOR_Y                  59145
#define ID_INDICATOR_TEXT_Z             59146
#define ID_INDICATOR_Z                  59147
#define ID_INDICATOR_TEXT_LAYER         59148
#define ID_INDICATOR_LAYER              59149
#define ID_INDICATOR_UNIT               59150
#define ID_INDICATOR_TEXT_UNIT          59151
#define ID_INDICATOR_TEXT_TIME          59152
#define ID_INDICATOR_TEXT_DATE          59153
#define ID_INDICATOR_DATE               59154
#define ID_INDICATOR_TIME               59155
#define ID_INDICATOR_TEXT_DRAWING       59156
#define ID_INDICATOR_DRAWING            59157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         32970
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
