echo insert Disk #1
pause
copy d:\drgraf\frame\*.cpp    b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.spp    b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.clw    b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.def    b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.rc     b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.mak    b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.bat    b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.h      b:\drgraf\frame\*.*
copy d:\drgraf\frame\*.sh     b:\drgraf\frame\*.*
copy d:\drgraf\frame\inc\*.h  b:\drgraf\frame\inc\*.*
copy d:\drgraf\frame\res\*.*  b:\drgraf\frame\res\*.*
copy d:\drgraf\frame\hlp\*.*  b:\drgraf\frame\hlp\*.*


