//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DDLGRSRC.RC
//
// 3Dlgrsrc.h : header file
//
#ifndef _3DLGRSRC_H
#define _3DLGRSRC_H 
///////////////////////////////////////////////////////////////////////////// 

#define IDS_CHECK_RESOURCE              1 

#define IDD_OK                          1
#define IDD_ESC                         9
#define IDC_EDIT                        152
#define IDC_DELETE                      151
#define IDD_AXIS                        120
#define IDC_SPIN_ROT                    121
#define IDC_SPIN_INCREMENT              127
#define IDC_TILT                        128
#define IDC_INCREMENT                   130
#define IDD_ADD                         141
#define IDD_DEL                         142
#define IDD_EDIT                        146
#define IDC_SAMPLE                      152
#define IDC_SPIN_TILT                   154
#define IDC_ROTATION                    155

#define IDD_EYEPOSITION                 504
#define IDC_BUTTON_TILT                 2201
#define IDC_BUTTON_ROTATION             2202
#define IDC_BUTTON_INCREMENT            2203
////////////////////////////////////////////

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
/////////////////////////////////////////////
#endif

