echo insert Disk #0
pause
copy d:\drgraf\allheads\*.cpp    b:\allheads\*.*
copy d:\drgraf\allheads\*.spp    b:\allheads\*.*
copy d:\drgraf\allheads\*.clw    b:\allheads\*.*
copy d:\drgraf\allheads\*.def    b:\allheads\*.*
copy d:\drgraf\allheads\*.rc     b:\allheads\*.*
copy d:\drgraf\allheads\*.mak    b:\allheads\*.*
copy d:\drgraf\allheads\*.bat    b:\allheads\*.*
copy d:\drgraf\allheads\*.h  	 b:\allheads\*.*
copy d:\drgraf\allheads\*.sh     b:\allheads\*.*
copy d:\drgraf\allheads\inc\*.h  b:\allheads\inc\*.*
copy d:\drgraf\allheads\res\*.*  b:\allheads\res\*.*
copy d:\drgraf\allheads\hlp\*.*  b:\allheads\hlp\*.*


