//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DataBase.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_CLOSED                      126
#define IDB_OPEN                        127
#define IDD_NODE_GEOM                   130
#define IDD_NODE_TOPO                   131
#define IDD_NODE_INPUT                  138
#define IDD_NODE_DEBUG                  139
#define IDD_NODE_LOAD                   140
#define IDD_NODE_SUPP                   141
#define IDD_NODE_DISP                   142
#define IDD_NODE_REST                   143
#define IDD_CPOOLLIST                   145
#define IDC_COORD                       400
#define IDC_DIRECTION                   401
#define IDD_NODE_ID                     402
#define IDD_NODE_TYPE                   403
#define IDD_NODE_DX                     404
#define IDD_NODE_DX2                    405
#define IDD_NODE_DY                     406
#define IDD_NODE_DY2                    407
#define IDD_NODE_DZ                     408
#define IDD_NODE_DZ2                    409
#define IDD_LENGTH                      415
#define IDC_NODEGEOM_TEXT               1001
#define IDD_CURVE_ID                    1003
#define IDD_CURVE_TYPE                  1004
#define IDD_MESH1D_ID                   1005
#define IDD_MESH1D_TYPE                 1006
#define IDD_MESH2D_ID                   1007
#define IDD_MESH2D_TYPE                 1008
#define IDD_MESH3D_ID                   1009
#define IDD_MESH3D_TYPE                 1010
#define IDD_PATCH_ID                    1011
#define IDD_PATCH_TYPE                  1012
#define IDD_PATCH_PROC                  1012
#define IDD_SOLID_ID                    1013
#define IDD_SUPP_ID                     1013
#define IDD_PATCH_SUBTYPE               1013
#define IDD_SOLID_TYPE                  1014
#define IDD_SUPP_TYPE                   1014
#define IDD_STAL_ID                     1015
#define IDD_STAL_TYPE                   1016
#define IDD_CUR_P_ID                    1017
#define IDD_CUR_P_TYPE                  1018
#define IDC_STALCOMBO                   1018
#define IDD_PAT_P_ID                    1019
#define IDC_SPELCOMBO                   1019
#define IDD_PAT_P_TYPE                  1020
#define IDD_OBJ3D_ID                    1021
#define IDC_SUPPCOMBO                   1021
#define IDD_OBJ3D_TYPE                  1022
#define IDC_NODECOMBO                   1022
#define IDD_MBJ3D_ID                    1023
#define IDC_CURVECOMBO                  1023
#define IDD_MBJ3D_TYPE                  1024
#define IDC_PATCHCOMBO                  1024
#define IDC_CURVECOMBO_U                1024
#define IDC_SOLIDCOMBO                  1025
#define IDC_CURVECOMBO_V                1025
#define IDC_OBJ3DCOMBO                  1026
#define IDC_CURVECOMBO_W                1026
#define IDC_FROM_IS_CN                  1027
#define IDC_MNODECOMBO                  1027
#define IDC_REF_IS_CN                   1028
#define IDC_MESH1DCOMBO                 1028
#define IDC_TO_IS_CN                    1029
#define IDC_MESH2DCOMBO                 1029
#define IDC_EDIT1                       1030
#define IDC_MESH3DCOMBO                 1030
#define IDC_REFNODEID                   1030
#define IDC_LOAD_TYPE                   1030
#define IDC_DEGREE                      1030
#define IDC_CURVATURECOMBO              1030
#define IDC_EDIT2                       1031
#define IDC_MBJ3DCOMBO                  1031
#define IDC_FROMID                      1031
#define IDC_CREATEBASE                  1031
#define IDC_CLASS                       1031
#define IDC_EDIT3                       1032
#define IDC_NODEORMNODE                 1032
#define IDC_TOID                        1032
#define IDC_ISOTO                       1032
#define IDC_CURVEORFE1D                 1033
#define IDC_NODE_IS_CN_MN               1033
#define IDC_BZSEGS                      1033
#define IDC_PATCHORFE2D                 1034
#define IDC_TOTELEMS                    1034
#define IDC_SOLIDORFE3D                 1035
#define IDC_TOTNODE_U                   1035
#define IDC_COR1DPROCOMBO               1036
#define IDC_RATIO                       1036
#define IDC_TOTNODE_V                   1036
#define IDC_CURVEORMESH1DPROF           1037
#define IDC_DOFX                        1037
#define IDC_TOTNODE_W                   1037
#define IDC_2DPROCOMBO                  1038
#define IDC_DOFY                        1038
#define IDC_MBJ3DPROCOMBO               1039
#define IDC_DOFZ                        1039
#define IDC_CURVMBJ3DPROF2              1040
#define IDC_DOFXR                       1040
#define IDC_3DPROCOMBO                  1041
#define IDC_DOFYR                       1041
#define IDC_DOFZR                       1042
#define IDC_NODETOPOCOMBO               1042
#define IDC_RELEASE                     1043
#define IDC_LOCALPOSX                   1044
#define IDC_LOCALPOSY                   1045
#define IDC_DYNLCOMBO                   1045
#define IDC_LOCALPOSZ                   1046
#define IDD_COORD_DX                    1046
#define IDC_NORMALWORLDX                1047
#define IDD_COORD_DY                    1047
#define IDC_NORMALWORLDY                1048
#define IDD_COORD_DZ                    1048
#define IDC_NORMALWORLDZ                1049
#define IDC_SUPPORT_TYPE                1049
#define IDC_M_PTX                       1050
#define IDC_SKEWED                      1050
#define IDC_M_PTY                       1051
#define IDC_INODECOMBO                  1051
#define IDC_WORLDPOSX                   1052
#define IDC_NORMAL2DX                   1053
#define IDC_CLOSED                      1053
#define IDC_NORMAL2DY                   1054
#define IDC_UNIFORM                     1054
#define IDC_WORLDPOSY                   1055
#define IDC_ISO                         1055
#define IDC_WORLDPOSZ                   1056
#define IDC_ELPERSEGCOMBO               1056
#define IDC_EYEPOSX                     1057
#define IDC_BCLEFT                      1057
#define IDC_EYEPOSY                     1058
#define IDC_CNODECOMBO                  1058
#define IDC_EYEPOSZ                     1059
#define IDC_BCRIGHT                     1059
#define IDC_ELEMCOMBO                   1059
#define IDC_SCREENPOS3DX                1060
#define IDC_KNOTTYPE                    1060
#define IDC_BSCNODECOMBO                1060
#define IDC_SCREENPOS3DY                1061
#define IDC_WEIGHTTYPE                  1061
#define IDC_ENODECOMBO                  1061
#define IDC_SCREENPOS3DZ                1062
#define IDC_TANX                        1062
#define IDC_BZWTSCOMBO                  1062
#define IDC_TANY                        1063
#define IDC_TANGENTCOMBO                1063
#define IDC_TANZ                        1064
#define IDC_BZKNOTCOMBO                 1064
#define IDC_CENTERX                     1065
#define IDC_BZCNODECOMBO                1065
#define IDC_CENTERY                     1066
#define IDC_CENTERZ                     1067
#define IDC_AXISX                       1068
#define IDC_AXISY                       1069
#define IDC_AXISZ                       1070
#define IDC_CIRCLETYPE                  1071
#define IDC_LENX                        1071
#define IDC_RADIUS                      1072
#define IDC_TOTANGLE                    1073
#define IDC_ANGPERSEGCOMBO              1074
#define IDC_LENY                        1075
#define IDC_LENZ                        1076
#define IDC_CLOSED_S                    1080
#define IDC_CLOSED_T                    1081
#define IDC_LATCHCOMBO                  1083
#define IDC_LATCHCOMBO_U                1084
#define IDC_LATCHCOMBO_V                1085
#define IDC_LATCHCOMBO_W                1086
#define IDC_CURVEORSPINE                1087
#define IDC_CURVEUORXSEC                1088
#define IDC_CURVEVORTWIST               1089
#define IDC_CURVEWORRAD                 1090
#define IDD_SUPPORT_ID                  1091
#define IDC_TANORNORMAL                 1093
#define IDC_SKEWDIRX                    1094
#define IDC_SKEWDIRY                    1095
#define IDC_SKEWDIRZ                    1096
#define IDC_STAL_TYPE                   1097
#define IDD_CURVE_GEOM                  1130
#define IDD_CURVE_TOPO                  1131
#define IDD_CURVE_INPUT                 1138
#define IDD_CURVE_DEBUG                 1139
#define IDD_CURVE_LOAD                  1140
#define IDD_CURVE_SUPP                  1141
#define IDD_CURVE_DISP                  1142
#define IDD_CURVE_REST                  1143
#define IDD_CUR_P_GEOM                  1144
#define IDD_CUR_P_TOPO                  1145
#define IDD_CUR_P_INPUT                 1146
#define IDD_CUR_P_DEBUG                 1147
#define IDD_CUR_P_LOAD                  1148
#define IDD_CUR_P_SUPP                  1149
#define IDD_CUR_P_DISP                  1150
#define IDD_CUR_P_REST                  1151
#define IDD_PATCH_GEOM                  1230
#define IDD_PATCH_TOPO                  1231
#define IDD_PATCH_INPUT                 1238
#define IDD_PATCH_DEBUG                 1239
#define IDD_PATCH_LOAD                  1240
#define IDD_PATCH_SUPP                  1241
#define IDD_PATCH_DISP                  1242
#define IDD_PATCH_REST                  1243
#define IDD_PAT_P_GEOM                  1244
#define IDD_PAT_P_TOPO                  1245
#define IDD_PAT_P_INPUT                 1246
#define IDD_PAT_P_DEBUG                 1247
#define IDD_PAT_P_LOAD                  1248
#define IDD_PAT_P_SUPP                  1249
#define IDD_PAT_P_DISP                  1250
#define IDD_PAT_P_REST                  1251
#define IDD_SOLID_GEOM                  1330
#define IDD_SOLID_TOPO                  1331
#define IDD_SOLID_INPUT                 1338
#define IDD_SOLID_DEBUG                 1339
#define IDD_SOLID_LOAD                  1340
#define IDD_SOLID_SUPP                  1341
#define IDD_SOLID_DISP                  1342
#define IDD_SOLID_REST                  1343
#define IDD_SUPP_DEFN                   1344
#define IDD_SUPP_INPUT                  1345
#define IDD_SUPP_DEBUG                  1346
#define IDD_STAL_DEFN                   1347
#define IDD_STAL_INPUT                  1348
#define IDD_STAL_DEBUG                  1349
#define IDD_MESH1D_GEOM                 1430
#define IDD_MESH1D_TOPO                 1431
#define IDD_MESH1D_INPUT                1438
#define IDD_MESH1D_DEBUG                1439
#define IDD_MESH1D_LOAD                 1440
#define IDD_MESH1D_SUPP                 1441
#define IDD_MESH1D_DISP                 1442
#define IDD_MESH1D_REST                 1443
#define IDD_MESH2D_GEOM                 1530
#define IDD_MESH2D_TOPO                 1531
#define IDD_MESH2D_INPUT                1538
#define IDD_MESH2D_DEBUG                1539
#define IDD_MESH2D_LOAD                 1540
#define IDD_MESH2D_SUPP                 1541
#define IDD_MESH2D_DISP                 1542
#define IDD_MESH2D_REST                 1543
#define IDD_MESH3D_GEOM                 1630
#define IDD_MESH3D_TOPO                 1631
#define IDD_MESH3D_INPUT                1638
#define IDD_MESH3D_DEBUG                1639
#define IDD_MESH3D_LOAD                 1640
#define IDD_MESH3D_SUPP                 1641
#define IDD_MESH3D_DISP                 1642
#define IDD_MESH3D_REST                 1643
#define IDD_MBJ3D_GEOM                  1730
#define IDD_MBJ3D_TOPO                  1731
#define IDD_MBJ3D_INPUT                 1738
#define IDD_MBJ3D_DEBUG                 1739
#define IDD_MBJ3D_LOAD                  1740
#define IDD_MBJ3D_SUPP                  1741
#define IDD_MBJ3D_DISP                  1742
#define IDD_MBJ3D_REST                  1743
#define IDD_OBJ3D_GEOM                  1830
#define IDD_OBJ3D_TOPO                  1831
#define IDD_OBJ3D_INPUT                 1838
#define IDD_OBJ3D_DEBUG                 1839
#define IDD_OBJ3D_LOAD                  1840
#define IDD_OBJ3D_SUPP                  1841
#define IDD_OBJ3D_DISP                  1842
#define IDD_OBJ3D_REST                  1843
#define IDS_NODEINT                     61204
#define IDS_CURVEINT                    61205
#define IDS_CURVEGEOM                   61206
#define IDS_NODEGEOM                    61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
