//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DDLGRSRC.RC
//
#define IDS_CHECK_RESOURCE              1
#define IDD_OK                          1
#define IDD_ESC                         9
#define IDD_AXIS                        120
#define IDC_SPIN_ROT                    121
#define IDC_SPIN_INCREMENT              127
#define IDC_TILT                        128
#define IDC_INCREMENT                   130
#define IDD_TEXT_INSERT                 138
#define IDD_LABEL_EDIT                  139
#define IDD_ADD                         141
#define IDD_DEL                         142
#define IDD_EDIT_LABEL                  144
#define IDD_EDIT                        146
#define IDD_LIST_LABEL                  148
#define IDC_EDIT_LABEL                  150
#define IDC_DELETE                      151
#define IDC_EDIT                        152
#define IDC_SAMPLE                      152
#define IDC_SPIN_TILT                   154
#define IDC_ROTATION                    155
#define IDC_TEXT_ANGLE                  160

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         161
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
