//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DDLGRSRC.RC
//
#define IDS_CHECK_RESOURCE              1
#define IDD_OK                          1
#define IDD_ESC                         9
#define IDD_AXIS                        120
#define IDC_SPIN_ROT                    121
#define IDC_SPIN_INCREMENT              127
#define IDC_TILT                        128
#define IDC_INCREMENT                   130
#define IDD_TEXT_INSERT                 138
#define IDD_LABEL_EDIT                  139
#define IDD_ADD                         141
#define IDD_DEL                         142
#define IDD_EDIT_LABEL                  144
#define IDD_EDIT                        146
#define IDD_LIST_LABEL                  148
#define IDC_EDIT_LABEL                  150
#define IDC_DELETE                      151
#define IDC_EDIT                        152
#define IDC_SAMPLE                      152
#define IDC_SPIN_TILT                   154
#define IDC_ROTATION                    155
#define IDD_AXISWND                     158
#define IDD_GRID                        159
#define IDC_TEXT_ANGLE                  160
#define IDC_PITCH                       160
#define IDC_ROLL                        161
#define IDC_YAW                         162
#define IDC_AXIS                        162
#define IDC_LEFT                        163
#define IDC_TOP                         164
#define IDC_RIGHT                       165
#define IDC_BOTTOM                      166
#define IDC_FRONT                       167
#define IDC_BACK                        168
#define IDC_FULL                        169
#define IDC_ROTATE                      170
#define IDC_ALIGN                       171
#define IDC_FOREGROUND                  175
#define IDC_BACKGROUND                  176
#define IDC_XCON                        177
#define IDC_ZCON                        178
#define IDC_YCON                        179
#define IDC_GRIDID                      180
#define IDC_ALIGN_NODE                  188
#define IDC_CNODE_FROM                  189
#define IDC_CNODE_TO                    191
#define IDC_CNODE_MIN                   192
#define IDC_STEP_X                      193
#define IDC_CNODE_MAX                   194
#define IDC_STEP_Y                      195
#define IDC_STEP_Z                      197

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         182
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
