//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DRGRAF.RC
//

#define IDS_CHECK_RESOURCE              1 

#define IDB_ELEMENT                     110
#define IDD_OK                          1
#define IDD_ESC                         9
#define IDC_DELETE                      151
#define IDD_LIST                        144
#define IDD_EDIT                        146
#define IDD_ADD                         141
#define IDD_DEL                         142
/////////////////////////////////////////// Node
#define IDD_ELP_NODE                    148
#define IDD_NODE_CONTROL                206
#define IDD_NODE_ID                     258
#define IDD_NODE_X                      260
#define IDD_NODE_Y                      261
#define IDD_NODE_Z                      262
#define IDD_NODE_NID_R                  264
#define IDD_NODE_SUP_ID                 267
/////////////////////////////////////////// Pipe
#define IDD_ELP_PIPE                    147
#define IDD_VALVE                       131
#define IDD_PIPE_LINE_ID                301
#define IDD_PIPE_PID                    303
#define IDD_PIPE_NID_I                  322
#define IDD_PIPE_NID_J                  323
#define IDD_PIPE_RID_I                  324
#define IDD_PIPE_RID_J                  325
#define IDD_PIPE_STRESS_ID_I            326
#define IDD_PIPE_STRESS_ID_J            327
#define IDD_PIPE_MID                    328
#define IDD_PIPE_NSEG                   304
/////////////////////////////////////////// Beam
#define IDD_ELP_BEAM                    150
#define IDD_BEAM_LINE_ID                401
#define IDD_BEAM_NID_I                  402
#define IDD_BEAM_NID_J                  403
#define IDD_BEAM_RID_I                  404
#define IDD_BEAM_RID_J                  405
#define IDD_BEAM_NID_K                  406
#define IDD_BEAM_PID                    407
#define IDD_BEAM_MID                    408
#define IDD_BEAM_NSEG                   409
/////////////////////////////////////////// Elbow
#define IDD_ELP_ELBOW                   149
#define IDD_ELBOW_LINE_ID               500
#define IDD_ELBOW_NID_I                 501
#define IDD_ELBOW_NID_J                 502
#define IDD_ELBOW_PID                   502
#define IDD_ELBOW_NID_CC                503
#define IDD_ELBOW_NID_TI                504
#define IDD_ELBOW_NID_A                 505
#define IDD_ELBOW_NID_B                 506
#define IDD_ELBOW_MID                   508
#define IDD_ELBOW_STRESS_ID_I           509
#define IDD_ELBOW_STRESS_ID_J           510
#define IDD_ELBOW_NSEG                  511
#define IDD_ELBOW_RID_I                 512
#define IDD_ELBOW_RID_J                 513
/////////////////////////////////////////// Supports
#define IDD_ELP_NLSUPPORT               151
#define IDD_ELP_SUPPORT                 109
#define IDD_SUPPORT_ID                  601
#define IDD_SUPPORT_KODE                622
#define IDD_SUPPORT_STIFFNESS           623
#define IDD_SUPPORT_NID_A               624
#define IDD_SUPPORT_TSPRING             625
#define IDD_SUPPORT_RSPRING             626
#define IDD_SUPPORT_TSNUBBER            627
#define IDD_SUPPORT_RSNUBBER            628
#define ID_EL_ROT_SPRING                119
#define IDD_NL_SUPP_ID                  701
#define IDD_NL_SUPP_KODE                702
#define IDD_NL_SUPP_STIFFNESS           703
#define IDD_NL_SUPP_NID_A               704
/////////////////////////////////////////// Plate
/////////////////////////////////////////// Shell
/////////////////////////////////////////// Truss
/////////////////////////////////////////// Plane

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
