//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DRGRAF.RC
//
#define IDD_OK                          1
#define IDD_ESC                         9
#define IDD_ADD                         141
#define IDD_DEL                         142
#define IDD_LIST                        144
#define IDR_MAINFRAME                   2
#define IDR_GRAFTYPE                    3
#define IDS_NEW_DRGRAF                  4
#define IDS_TOO_MANY_ROWS				111
#define IDR_12TYPE                      5
#define IDR_23TYPE                      6
#define IDR_31TYPE                      7
#define IDR_ISOTYPE                     8
#define IDR_DATATYPE                    9
#define IDD_FILE_PATH                   12
#define IDD_PARAMETERS_XMIN             71
#define IDD_PARAMETERS_XMAX             72
#define IDD_PARAMETERS_YMIN             73
#define IDD_PARAMETERS_YMAX             74
#define IDD_PARAMETERS_FACTOR           75
#define IDD_PARAMETERS_FIX              76
#define IDS_TOP_STATUSBAR               111
#define IDC_DRAW_ALLACTIVE              112
#define IDS_BOT_STATUSBAR               112
#define IDC_DRG_CURSOR                  131
#define IDD_EDIT                        146
#define IDC_DELETE                      151
#define IDC_EDIT                        152
#define IDR_OPENMENU                    156
#define IDR_INITMENU                    157
#define IDD_ABOUTBOX                    200
#define IDC_DISK_SPACE                  207
#define IDC_AVAIL_MEM                   259
#define IDC_LICENSEE_COMPANY            263
#define IDC_LICENSEE_NAME               265
#define IDD_SPLASH                      266
#define IDC_MATH_COPR                   269
#define IDC_BIGICON                     1008
#define IDS_DISK_SPACE                  1009
#define IDS_MATH_COPR_NOTPRESENT        1010
#define IDS_MATH_COPR_PRESENT           1011
#define IDS_AVAIL_MEM                   1012
#define IDS_LICENSEE_COMPANY            1013
#define IDS_LICENSEE_NAME               1014
#define IDS_DISK_SPACE_UNAVAIL          1018
#define IDM_VIEW_ISOVIEW                32751
#define IDM_DRAW_EYELEVEL               32752
#define IDM_DRAW_LAYER                  32753
#define IDM_DRAW_DRAWBOX                32754
#define IDM_VIEW_12VIEW                 32768
#define IDM_VIEW_23VIEW                 32769
#define IDM_VIEW_31VIEW                 32770
#define IDM_ISO_VIEW                    32771
#define IDM_DRAW_UNIT                   32774
#define IDM_DRAW_PAPER                  32775
#define IDM_DRAW_PRECISION              32776
#define IDM_DRAW_ELEMENTBOX             32777
#define IDM_DRAW_AXIS                   32778
#define IDM_DRAW_UNITS                  32779
#define IDM_DRAW_EYEPOSITION            32780
#define IDM_DRAW_SCALEFACTOR            32781
#define IDM_DEFAULT_NEW                 32782
#define IDM_DEFAULT_CURRENT             32783
#define IDM_OPTION_CURSOR               32784
#define ID_DRAW_MAG_XMAG                32785
#define IDM_DRAW_MAG_XMAG               32785
#define ID_DRAW_MAG_YMAG                32786
#define ID_DRAW_MAG_ZMAG                32788
#define IDM_VIEW_DRAWBOX                32789
#define IDM_VIEW_ELEMENTBOX             32790
#define IDM_OPTION_DIALOG               32791
#define ID_OPTION_REFRESH               32792
#define IDM_DRAW_MAG_YMAG               32793
#define ID_OPTION_AXISON                32794
#define IDM_OPTION_DIALOGON             32795
#define IDM_EDIT_CLEARALL               32797
#define IDM_OPTION_RUBBERBAND           32798
#define IDM_SCALE                       32799
#define IDM_ZOOM_IN                     32800
#define IDM_ZOOM_OUT                    32801
#define IDM_ZOOM_FIT                    32802
#define IDM_ZOOM                        32820
#define IDM_OPTIONS_PENCHANGE           32821
#define ID_VIEW_STATUS_BAR_T            32822
#define ID_VIEW_CARDDECK                32823
#define ID_DECK_DREAMPIPE               32825
#define ID_DECK_SAP                     32826
#define ID_DECK_TAB                     32827
#define IDM_VIEW_CARDDECK               32828
#define IDM_VIEW_DATAVIEW               32828
#define IDM_DECK_DREAMPIPE              32829
#define IDM_DECK_SAP                    32830
#define IDM_DECK_TAB                    32831
#define IDM_VIEW_S_BAR_BOT              32832
#define IDM_VIEW_S_BAR_TOP              32833
#define ID_INDICATOR_TEXT_X             59142
#define ID_INDICATOR_X                  59143
#define ID_INDICATOR_TEXT_Y             59144
#define ID_INDICATOR_Y                  59145
#define ID_INDICATOR_TEXT_Z             59146
#define ID_INDICATOR_Z                  59147
#define ID_INDICATOR_TEXT_LAYER         59148
#define ID_INDICATOR_LAYER              59149
#define ID_INDICATOR_UNIT               59150
#define ID_INDICATOR_TEXT_UNIT          59151
#define ID_INDICATOR_TEXT_TIME          59152
#define ID_INDICATOR_TEXT_DATE          59153
#define ID_INDICATOR_DATE               59154
#define ID_INDICATOR_TIME               59155
#define ID_INDICATOR_TEXT_DRAWING       59156
#define ID_INDICATOR_DRAWING            59157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
