//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DRGRAF.RC
//
///////////////////////////////////////////////////////////////////////////// 

#define IDS_CHECK_RESOURCE              1 

#define IDD_OK                          1
#define IDD_ESC                         9
#define IDC_DRAW_LIST                   111
#define IDC_DRAW_ALLACTIVE              112
#define IDC_TOGGLE_ALL                  113
#define IDD_PATCH                       122
#define IDD_OBJ3D                       123
#define IDD_ADD                         141
#define IDD_DEL                         142
#define IDD_LIST                        144
#define IDD_EDIT                        146
#define IDC_DELETE                      151
#define IDC_EDIT                        152
#define IDC_CURRENT                     159
#define IDC_CHANGE                      153
#define IDC_COMBO_STYLE                 160

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
