//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by TEMP.RC
//
#define IDC_SAMPLE                      131

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        127
#define _APS_NEXT_COMMAND_VALUE         32789
#define _APS_NEXT_CONTROL_VALUE         132
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
