echo off
echo insert Disk #3
pause
copy d:\drgraf\spec_dlg\*.cpp    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.spp    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.clw    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.def    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.rc     b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.rc2    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.mak    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.bat    b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.h      b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\*.sh      b:\spec_dlg\*.*
copy d:\drgraf\spec_dlg\dlg\*.*  b:\spec_dlg\dlg\*.*
copy d:\drgraf\spec_dlg\res\*.*  b:\spec_dlg\res\*.*
copy d:\drgraf\spec_dlg\hlp\*.*  b:\spec_dlg\hlp\*.*
echo on

