echo insert Disk #4
pause
copy d:\drgraf\toolboxs\inc\*.h     	       b:\inc\*.*
copy d:\drgraf\toolboxs\dboxebox\*.sh          b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.h           b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.spp         b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\inc\*.h       b:\dboxebox\inc\*.*
copy d:\drgraf\toolboxs\dboxebox\*.cpp         b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.clw         b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.def         b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.rc          b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.mak         b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\*.bat         b:\dboxebox\*.*
copy d:\drgraf\toolboxs\dboxebox\res\*.*       b:\drgraf\toolboxs\dboxebox\res\*.*
copy d:\drgraf\toolboxs\dboxebox\hlp\*.*       b:\drgraf\toolboxs\dboxebox\hlp\*.*
