//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DBOXEBOX.RC
//
#define IDR_MAINFRAME                   2
#define IDR_DBOXEBTYPE                  3
#define IDD_ABOUTBOX                    100

#define IDS_CHECK_RESOURCE              201
#define IDC_BUTTON                      211

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#define _APS_NEXT_COMMAND_VALUE         32771
