echo insert Disk #4
pause
copy d:\drgraf\toolboxs\drawbox\*.h            b:\drawbox\inc\*.*
copy d:\drgraf\toolboxs\drawbox\*.sh           b:\drawbox\inc\*.*
copy d:\drgraf\toolboxs\drawbox\inc\*.h        b:\drawbox\inc\*.*
copy d:\drgraf\toolboxs\drawbox\*.cpp          b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\*.spp          b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\*.clw          b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\*.def          b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\*.rc           b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\*.mak          b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\*.bat          b:\drawbox\*.*
copy d:\drgraf\toolboxs\drawbox\res\*.*        b:\drawbox\res\*.*
copy d:\drgraf\toolboxs\drawbox\hlp\*.*        b:\drgraf\toolboxs\drawbox\hlp\*.*


