#ifndef _DBOXBUTT_H
#define _DBOXBUTT_H
///////////////////////////////////////////////////////////// GLOBALS
#define DB_BUTT_COUNT   16
#define DB_MAX_BUTT_COL 3  // must be SUBMULTIPLE of MAX_SQ_COL
//////////////////////// color square
#define DB_MAX_SQ_ROW	 4
#define DB_MAX_SQ_COL	 6
//////////////////////////////// DRAWBOX ButtonSize
#define DB_BNSIZE_CX		40
#define	DB_BNSIZE_CY		40
#define	DB_IMAGE_CX			32 
#define	DB_IMAGE_CY			30
//////////////////////////////// Color Square
#define	DB_COLOR_BNSIZE		DB_BNSIZE_CX/2    
/////////////////////////////////////////////////////////////////////////////
#endif 

