echo insert Disk #1
pause
copy d:\drgraf\view\*.cpp    b:\drgraf\view\*.*
copy d:\drgraf\view\*.clw    b:\drgraf\view\*.*
copy d:\drgraf\view\*.def    b:\drgraf\view\*.*
copy d:\drgraf\view\*.rc     b:\drgraf\view\*.*
copy d:\drgraf\view\*.mak    b:\drgraf\view\*.*
copy d:\drgraf\view\*.bat    b:\drgraf\view\*.*
copy d:\drgraf\view\*.h      b:\drgraf\view\*.*
copy d:\drgraf\view\res\*.*  b:\drgraf\view\res\*.*
copy d:\drgraf\view\hlp\*.*  b:\drgraf\view\hlp\*.*


