echo insert Disk #4
pause
copy d:\drgraf\toolboxs\elembox\inc\*.h        b:\elembox\inc\*.*
copy d:\drgraf\toolboxs\elembox\*.h 	       b:\elembox\inc\*.*
copy d:\drgraf\toolboxs\elembox\*.sh 	       b:\elembox\inc\*.*
copy d:\drgraf\toolboxs\elembox\*.cpp          b:\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.spp          b:s\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.clw          b:\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.def          b:\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.rc           b:\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.mak          b:\elembox\*.*
copy d:\drgraf\toolboxs\elembox\*.bat          b:\elembox\*.*
copy d:\drgraf\toolboxs\elembox\res\*.*        b:\elembox\res\*.*
copy d:\drgraf\toolboxs\elembox\hlp\*.*        b:\drgraf\toolboxs\elembox\hlp\*.*


