echo insert Disk #2
pause
copy d:\drgraf\draw3d\*.cpp    b:\draw3d\*.*
copy d:\drgraf\draw3d\*.spp    b:\draw3d\*.*
copy d:\drgraf\draw3d\*.clw    b:\draw3d\*.*
copy d:\drgraf\draw3d\*.def    b:\draw3d\*.*
copy d:\drgraf\draw3d\*.rc     b:\draw3d\*.*
copy d:\drgraf\draw3d\*.mak    b:\draw3d\*.*
copy d:\drgraf\draw3d\*.bat    b:\draw3d\*.*
copy d:\drgraf\draw3d\*.h      b:\draw3d\*.*
copy d:\drgraf\draw3d\*.sh     b:\draw3d\*.*
copy d:\drgraf\draw3d\inc\*.h  b:\draw3d\inc\*.*
copy d:\drgraf\draw3d\res\*.*  b:\draw3d\res\*.*
copy d:\drgraf\draw3d\hlp\*.*  b:\draw3d\hlp\*.*


