//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DRGRAF.RC
//

#define IDS_CHECK_RESOURCE              1 

#define IDD_OK                          1
#define IDD_ESC                         9
#define IDC_DELETE                      151
#define IDD_LIST                        144
#define IDD_EDIT                        146
#define IDD_ADD                         141
#define IDD_DEL                         142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32834
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
