echo insert Disk #7
pause
copy d:\drgraf\mousemgr\*.cpp    b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.spp    b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.clw    b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.def    b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.rc     b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.mak    b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.bat    b:\mousemgr\*.*
copy d:\drgraf\mousemgr\inc\*.h  b:\mousemgr\inc\*.*
copy d:\drgraf\mousemgr\*.h      b:\mousemgr\*.*
copy d:\drgraf\mousemgr\*.sh     b:\mousemgr\*.*
copy d:\drgraf\mousemgr\res\*.*  b:\mousemgr\res\*.*
copy d:\drgraf\mousemgr\hlp\*.*  b:\drgraf\mousemgr\hlp\*.*


