echo insert Disk #5
pause
copy d:\drgraf\elemobjs\*.cpp    b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.spp    b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.clw    b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.def    b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.rc     b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.mak    b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.bat    b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.h  	 b:\elemobjs\*.*
copy d:\drgraf\elemobjs\*.sh  	 b:\elemobjs\*.*
copy d:\drgraf\elemobjs\res\*.*  b:\elemobjs\res\*.*
copy d:\drgraf\elemobjs\hlp\*.*  b:\elemobjs\hlp\*.*


